# Prometheus Configuration for i3 8th Gen - Ultra Lightweight
# Optimized for minimal resource usage on 4GB RAM systems

global:
  scrape_interval: 30s        # Reduced frequency for i3
  evaluation_interval: 60s    # Less frequent rule evaluation
  external_labels:
    monitor: 'supreme-system-v5-i3'
    environment: 'i3-optimized'

# Minimal rule evaluation for i3
rule_files:
  - "alert_rules_i3.yml"  # Simplified rules

# Lightweight scrape configuration
scrape_configs:
  # Supreme System V5 with reduced frequency
  - job_name: 'supreme-system-v5-i3'
    static_configs:
      - targets: ['supreme-system-v5-i3:9090']
    metrics_path: '/metrics'
    scrape_interval: 15s      # Higher frequency for main app
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']
    # Reduce metric cardinality
    metric_relabel_configs:
      # Keep only essential metrics for i3
      - source_labels: [__name__]
        regex: 'supreme_(api_latency_milliseconds|websocket_clients_total|trading_loop_milliseconds|orders_executed_total|pnl_daily_usd|exchange_connectivity|gross_exposure_usd|max_drawdown_percent).*'
        action: keep
      # Drop high-cardinality labels
      - regex: 'instance'
        action: labeldrop

  # Prometheus self-monitoring (reduced)
  - job_name: 'prometheus-i3'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 60s      # Much less frequent
    metric_relabel_configs:
      # Keep only essential Prometheus metrics
      - source_labels: [__name__]
        regex: 'prometheus_(tsdb_head_samples_appended_total|tsdb_head_series|config_last_reload_successful)'
        action: keep

  # Redis metrics (minimal)
  - job_name: 'redis-i3'
    static_configs:
      - targets: ['supreme-redis-i3:6379']
    scrape_interval: 60s      # Low frequency
    scrape_timeout: 5s
    # Only basic Redis metrics
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'redis_(connected_clients|used_memory_bytes|keyspace_hits_total)'
        action: keep

# Disabled for i3 to save resources
# Node exporter, cAdvisor etc. are commented out
# Uncomment only if absolutely necessary

# - job_name: 'node-exporter-i3'
#   static_configs:
#     - targets: ['node-exporter:9100']
#   scrape_interval: 120s     # Very infrequent
#   metric_relabel_configs:
#     - source_labels: [__name__]
#       regex: 'node_(cpu_seconds_total|memory_MemTotal_bytes|memory_MemAvailable_bytes|load1)'
#       action: keep

# Remote write disabled for i3 to save resources
# remote_write: []