name: ULTRA SFL - Final Verification & Release

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  verify-and-release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Quality gates (format/lint/imports)
        run: |
          black --check .
          ruff check .
          isort --check-only .

      - name: Run unit + integration tests
        run: |
          pytest -q

      - name: Build Rust (optional)
        run: |
          pip install maturin
          maturin develop --release || true

      - name: Package artifacts
        run: |
          mkdir -p artifacts
          cp -r htmlcov artifacts/ || true
          cp coverage.xml artifacts/ || true
          echo "Build completed at $(date)" > artifacts/build_info.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ultra-sfl-artifacts
          path: artifacts
