# python/supreme_system_v5/strategies.py
"""
Optimized Scalping Strategy using ultra-efficient technical analysis.
Memory-efficient, event-driven, mathematically equivalent.
ULTRA SFL implementation with enterprise-grade signal generation.
"""

from typing import Dict, List, Optional, Any, Tuple
import time
from enum import Enum
from dataclasses import dataclass, field
from .optimized.analyzer import OptimizedTechnicalAnalyzer
from .risk import SignalConfidence

from loguru import logger
from prometheus_client import Counter, Histogram

# Metrics
SIGNALS_GENERATED = Counter(
    "strategy_signals_total",
    "Signals generated by strategy",
    ["strategy", "signal_type"],
)
SIGNAL_CONFIDENCE = Histogram(
    "strategy_signal_confidence", "Signal confidence distribution", ["strategy"]
)
STRATEGY_LATENCY = Histogram(
    "strategy_latency_seconds", "Strategy calculation latency", ["strategy"]
)


class SignalType(Enum):
    """Trading signal types"""

    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"
    CLOSE_LONG = "CLOSE_LONG"
    CLOSE_SHORT = "CLOSE_SHORT"


@dataclass
class TradingSignal:
    """Trading signal with comprehensive metadata"""

    symbol: str
    signal_type: SignalType
    confidence: float  # 0.0 to 1.0
    entry_price: float
    stop_loss: float
    take_profit: float
    quantity: float
    reasoning: str
    indicators: Dict[str, Any] = field(default_factory=dict)
    timestamp: float = field(default_factory=time.time)

    def __post_init__(self):
        """Validate signal parameters"""
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError(
                f"Confidence must be between 0.0 and 1.0, got {self.confidence}"
            )

        if self.quantity <= 0:
            raise ValueError(f"Quantity must be positive, got {self.quantity}")


@dataclass
class MarketData:
    """Market data structure for strategy calculations"""

    symbol: str
    price: float
    volume: float
    timestamp: float
    bid: Optional[float] = None
    ask: Optional[float] = None
    high_24h: Optional[float] = None
    low_24h: Optional[float] = None


class TechnicalIndicators:
    """Technical indicator calculations with Rust acceleration"""

    @staticmethod
    def calculate_ema(prices: List[float], period: int) -> List[float]:
        """
        Calculate Exponential Moving Average
        Uses Rust implementation for maximum performance
        """
        if len(prices) < period:
            return []

        try:
            # Try Rust implementation first
            import numpy as np
            import supreme_engine_rs

            price_array = np.array(prices, dtype=np.float64)
            result = supreme_engine_rs.fast_ema(price_array, period)
            return result.tolist()

        except (ImportError, Exception) as e:
            logger.debug(f"Rust EMA not available, using Python fallback: {e}")
            return TechnicalIndicators._calculate_ema_python(prices, period)

    @staticmethod
    def _calculate_ema_python(prices: List[float], period: int) -> List[float]:
        """Python fallback for EMA calculation"""
        if len(prices) < period:
            return []

        multiplier = 2.0 / (period + 1)
        ema_values = []

        # First EMA is SMA
        sma = sum(prices[:period]) / period
        ema_values.append(sma)

        # Calculate subsequent EMAs
        for price in prices[period:]:
            ema = (price * multiplier) + (ema_values[-1] * (1 - multiplier))
            ema_values.append(ema)

        return ema_values

    @staticmethod
    def calculate_rsi(prices: List[float], period: int = 14) -> List[float]:
        """
        Calculate Relative Strength Index
        Uses Rust implementation for maximum performance
        """
        if len(prices) < period + 1:
            return []

        try:
            # Try Rust implementation first
            import numpy as np
            import supreme_engine_rs

            price_array = np.array(prices, dtype=np.float64)
            result = supreme_engine_rs.fast_rsi(price_array, period)
            return result.tolist()

        except (ImportError, Exception) as e:
            logger.debug(f"Rust RSI not available, using Python fallback: {e}")
            return TechnicalIndicators._calculate_rsi_python(prices, period)

    @staticmethod
    def _calculate_rsi_python(prices: List[float], period: int = 14) -> List[float]:
        """Python fallback for RSI calculation"""
        if len(prices) < period + 1:
            return []

        rsi_values = []
        gains = []
        losses = []

        # Calculate price changes
        for i in range(1, len(prices)):
            change = prices[i] - prices[i - 1]
            gains.append(max(change, 0))
            losses.append(max(-change, 0))

        # Calculate initial averages
        avg_gain = sum(gains[:period]) / period
        avg_loss = sum(losses[:period]) / period

        # Calculate first RSI
        if avg_loss == 0:
            rsi = 100.0
        else:
            rs = avg_gain / avg_loss
            rsi = 100 - (100 / (1 + rs))
        rsi_values.append(rsi)

        # Calculate subsequent RSIs using Wilder's smoothing
        for i in range(period, len(gains)):
            gain = gains[i]
            loss = losses[i]

            avg_gain = ((avg_gain * (period - 1)) + gain) / period
            avg_loss = ((avg_loss * (period - 1)) + loss) / period

            if avg_loss == 0:
                rsi = 100.0
            else:
                rs = avg_gain / avg_loss
                rsi = 100 - (100 / (1 + rs))

            rsi_values.append(rsi)

        return rsi_values

    @staticmethod
    def calculate_sma(prices: List[float], period: int) -> List[float]:
        """Calculate Simple Moving Average"""
        if len(prices) < period:
            return []

        try:
            # Try Rust implementation first
            import numpy as np
            import supreme_engine_rs

            price_array = np.array(prices, dtype=np.float64)
            result = supreme_engine_rs.fast_sma(price_array, period)
            return result.tolist()

        except (ImportError, Exception) as e:
            logger.debug(f"Rust SMA not available, using Python fallback: {e}")
            return TechnicalIndicators._calculate_sma_python(prices, period)

    @staticmethod
    def _calculate_sma_python(prices: List[float], period: int) -> List[float]:
        """Python fallback for SMA calculation"""
        if len(prices) < period:
            return []

        sma_values = []
        for i in range(period - 1, len(prices)):
            sma = sum(prices[i - period + 1 : i + 1]) / period
            sma_values.append(sma)

        return sma_values

    @staticmethod
    def calculate_macd(
        prices: List[float],
        fast_period: int = 12,
        slow_period: int = 26,
        signal_period: int = 9,
    ) -> Tuple[List[float], List[float], List[float]]:
        """Calculate MACD with signal line and histogram"""
        try:
            # Try Rust implementation first
            import numpy as np
            import supreme_engine_rs

            price_array = np.array(prices, dtype=np.float64)
            macd_line, signal_line, histogram = supreme_engine_rs.fast_macd(
                price_array, fast_period, slow_period, signal_period
            )
            return macd_line.tolist(), signal_line.tolist(), histogram.tolist()

        except (ImportError, Exception) as e:
            logger.debug(f"Rust MACD not available, using Python fallback: {e}")
            return TechnicalIndicators._calculate_macd_python(
                prices, fast_period, slow_period, signal_period
            )

    @staticmethod
    def _calculate_macd_python(
        prices: List[float],
        fast_period: int = 12,
        slow_period: int = 26,
        signal_period: int = 9,
    ) -> Tuple[List[float], List[float], List[float]]:
        """Python fallback for MACD calculation"""
        if len(prices) < slow_period:
            return [], [], []

        # Calculate EMAs
        fast_ema = TechnicalIndicators.calculate_ema(prices, fast_period)
        slow_ema = TechnicalIndicators.calculate_ema(prices, slow_period)

        # Calculate MACD line
        macd_line = []
        for i in range(len(slow_ema)):
            fast_idx = i + (slow_period - fast_period)
            if fast_idx < len(fast_ema):
                macd_line.append(fast_ema[fast_idx] - slow_ema[i])

        # Calculate signal line
        signal_line = TechnicalIndicators.calculate_ema(macd_line, signal_period)

        # Calculate histogram
        histogram = []
        for i in range(len(signal_line)):
            macd_idx = i + (signal_period - 1)
            if macd_idx < len(macd_line):
                histogram.append(macd_line[macd_idx] - signal_line[i])

        return macd_line, signal_line, histogram

    @staticmethod
    def calculate_bollinger_bands(
        prices: List[float], period: int = 20, std_dev: float = 2.0
    ) -> Tuple[List[float], List[float], List[float]]:
        """Calculate Bollinger Bands"""
        try:
            # Try Rust implementation first
            import numpy as np
            import supreme_engine_rs

            price_array = np.array(prices, dtype=np.float64)
            upper_band, middle_band, lower_band = supreme_engine_rs.bollinger_bands(
                price_array, period, std_dev
            )
            return upper_band.tolist(), middle_band.tolist(), lower_band.tolist()

        except (ImportError, Exception) as e:
            logger.debug(
                f"Rust Bollinger Bands not available, using Python fallback: {e}"
            )
            return TechnicalIndicators._calculate_bollinger_bands_python(
                prices, period, std_dev
            )

    @staticmethod
    def _calculate_bollinger_bands_python(
        prices: List[float], period: int = 20, std_dev: float = 2.0
    ) -> Tuple[List[float], List[float], List[float]]:
        """Python fallback for Bollinger Bands calculation"""
        if len(prices) < period:
            return [], [], []

        sma_values = TechnicalIndicators.calculate_sma(prices, period)
        upper_band = []
        lower_band = []

        for i, sma in enumerate(sma_values):
            start_idx = i
            end_idx = i + period

            # Calculate standard deviation
            values = prices[start_idx:end_idx]
            variance = sum((x - sma) ** 2 for x in values) / period
            std = variance**0.5

            upper_band.append(sma + std_dev * std)
            lower_band.append(sma - std_dev * std)

        return upper_band, sma_values, lower_band

    @staticmethod
    def calculate_vwap(
        high: List[float], low: List[float], close: List[float], volume: List[float]
    ) -> List[float]:
        """Calculate Volume Weighted Average Price"""
        try:
            # Try Rust implementation first
            import numpy as np
            import supreme_engine_rs

            high_array = np.array(high, dtype=np.float64)
            low_array = np.array(low, dtype=np.float64)
            close_array = np.array(close, dtype=np.float64)
            volume_array = np.array(volume, dtype=np.float64)

            result = supreme_engine_rs.volume_weighted_average_price(
                high_array, low_array, close_array, volume_array
            )
            return result.tolist()

        except (ImportError, Exception) as e:
            logger.debug(f"Rust VWAP not available, using Python fallback: {e}")
            return TechnicalIndicators._calculate_vwap_python(high, low, close, volume)

    @staticmethod
    def _calculate_vwap_python(
        high: List[float], low: List[float], close: List[float], volume: List[float]
    ) -> List[float]:
        """Python fallback for VWAP calculation"""
        if len(high) != len(low) or len(low) != len(close) or len(close) != len(volume):
            return []

        vwap_values = []
        cumulative_volume = 0.0
        cumulative_volume_price = 0.0

        for i in range(len(close)):
            typical_price = (high[i] + low[i] + close[i]) / 3.0
            volume_price = typical_price * volume[i]

            cumulative_volume += volume[i]
            cumulative_volume_price += volume_price

            if cumulative_volume > 0.0:
                vwap_values.append(cumulative_volume_price / cumulative_volume)
            else:
                vwap_values.append(typical_price)

        return vwap_values


class MultiTimeframeConfirmation:
    """Multi-timeframe analysis for signal confirmation"""

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self.config = config or {
            "higher_tf_ema_period": 21,  # 21-period EMA on higher timeframe
            "lower_tf_ema_period": 5,    # 5-period EMA on lower timeframe
            "trend_alignment_threshold": 0.7,  # Minimum alignment score
            "higher_tf_weight": 0.6,     # Weight for higher timeframe
            "lower_tf_weight": 0.4,      # Weight for lower timeframe
        }

    def analyze_trend_alignment(self, symbol: str, strategy_instance) -> float:
        """
        Analyze trend alignment across timeframes
        Returns alignment score between 0-1 (1 = perfect alignment)
        """
        try:
            # Get higher timeframe data (simulated - would use different resolution)
            # For now, we'll use a subset of the data to simulate higher TF
            price_history = strategy_instance.price_history.get(symbol, [])
            if len(price_history) < 50:
                return 0.5  # Neutral if insufficient data

            # Simulate higher timeframe by taking every 4th point
            higher_tf_prices = [price for i, (ts, price, vol) in enumerate(price_history) if i % 4 == 0]
            if len(higher_tf_prices) < 20:
                return 0.5

            higher_tf_prices = higher_tf_prices[-50:]  # Last 50 points for higher TF

            # Calculate EMAs for both timeframes
            lower_tf_ema = TechnicalIndicators.calculate_ema(
                [p for ts, p, vol in price_history[-50:]], self.config["lower_tf_ema_period"]
            )
            higher_tf_ema = TechnicalIndicators.calculate_ema(
                higher_tf_prices, self.config["higher_tf_ema_period"]
            )

            if not lower_tf_ema or not higher_tf_ema:
                return 0.5

            # Get latest EMA values
            latest_lower_ema = lower_tf_ema[-1] if lower_tf_ema else 0
            latest_higher_ema = higher_tf_ema[-1] if higher_tf_ema else 0

            # Get current price
            current_price = price_history[-1][1] if price_history else 0

            if current_price == 0:
                return 0.5

            # Calculate trend directions
            lower_tf_trend = 1 if current_price > latest_lower_ema else -1
            higher_tf_trend = 1 if current_price > latest_higher_ema else -1

            # Perfect alignment = 1.0, opposite = 0.0
            alignment = 1.0 if lower_tf_trend == higher_tf_trend else 0.0

            # Weight the alignment
            weighted_alignment = (
                alignment * self.config["higher_tf_weight"] +
                alignment * self.config["lower_tf_weight"]
            )

            return max(0.0, min(1.0, weighted_alignment))

        except Exception as e:
            logger.warning(f"Multi-timeframe analysis error for {symbol}: {e}")
            return 0.5  # Neutral on error


class VolatilityFilter:
    """Volatility-based signal filtering"""

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self.config = config or {
            "atr_period": 14,
            "min_volatility_threshold": 0.005,   # 0.5% minimum volatility
            "max_volatility_threshold": 0.05,    # 5% maximum volatility (too noisy)
            "volatility_lookback": 20,           # Periods to look back for volatility
            "high_volatility_penalty": 0.3,      # Reduce signal strength in high vol
            "low_volatility_boost": 1.2,         # Boost signal strength in low vol
        }

    def calculate_atr(self, highs: List[float], lows: List[float], closes: List[float], period: int = 14) -> List[float]:
        """Calculate Average True Range"""
        if len(highs) != len(lows) or len(lows) != len(closes):
            return []

        atr_values = []
        for i in range(len(closes)):
            if i < period - 1:
                atr_values.append(0.0)
                continue

            # True Range calculation
            tr1 = highs[i] - lows[i]
            tr2 = abs(highs[i] - closes[i-1]) if i > 0 else tr1
            tr3 = abs(lows[i] - closes[i-1]) if i > 0 else tr1

            true_range = max(tr1, tr2, tr3)

            if i == period - 1:
                # First ATR is simple average
                atr_values.append(sum([
                    max(highs[j] - lows[j],
                        abs(highs[j] - closes[j-1]) if j > 0 else highs[j] - lows[j],
                        abs(lows[j] - closes[j-1]) if j > 0 else highs[j] - lows[j])
                    for j in range(period)
                ]) / period)
            else:
                # Smoothed ATR
                prev_atr = atr_values[-1]
                atr_values.append((prev_atr * (period - 1) + true_range) / period)

        return atr_values

    def analyze_market_volatility(self, symbol: str, strategy_instance) -> Dict[str, Any]:
        """Analyze current market volatility conditions"""
        try:
            price_history = strategy_instance.price_history.get(symbol, [])
            if len(price_history) < self.config["volatility_lookback"] + 10:
                return {
                    "volatility_level": "insufficient_data",
                    "atr_value": 0.0,
                    "volatility_percent": 0.0,
                    "signal_multiplier": 1.0,
                    "filter_passed": True
                }

            # Extract OHLC data
            closes = [price for ts, price, vol in price_history]
            highs = []
            lows = []

            # Estimate highs/lows from price history (simplified)
            for i, (ts, price, vol) in enumerate(price_history):
                # Use neighboring prices to estimate HL
                if i > 0 and i < len(price_history) - 1:
                    prev_price = price_history[i-1][1]
                    next_price = price_history[i+1][1]
                    high = max(price, prev_price, next_price) * 1.002  # Add small buffer
                    low = min(price, prev_price, next_price) * 0.998
                else:
                    high = price * 1.002
                    low = price * 0.998

                highs.append(high)
                lows.append(low)

            # Calculate ATR
            atr_values = self.calculate_atr(highs, lows, closes, self.config["atr_period"])
            current_atr = atr_values[-1] if atr_values else 0.0

            # Calculate volatility as percentage
            current_price = closes[-1]
            volatility_percent = (current_atr / current_price) if current_price > 0 else 0.0

            # Determine volatility level
            if volatility_percent < self.config["min_volatility_threshold"]:
                volatility_level = "low"
                signal_multiplier = self.config["low_volatility_boost"]
            elif volatility_percent > self.config["max_volatility_threshold"]:
                volatility_level = "high"
                signal_multiplier = self.config["high_volatility_penalty"]
            else:
                volatility_level = "normal"
                signal_multiplier = 1.0

            # Determine if signal should pass filter
            filter_passed = (
                self.config["min_volatility_threshold"] <= volatility_percent <= self.config["max_volatility_threshold"]
            )

            return {
                "volatility_level": volatility_level,
                "atr_value": current_atr,
                "volatility_percent": volatility_percent,
                "signal_multiplier": signal_multiplier,
                "filter_passed": filter_passed
            }

        except Exception as e:
            logger.warning(f"Volatility analysis error for {symbol}: {e}")
            return {
                "volatility_level": "error",
                "atr_value": 0.0,
                "volatility_percent": 0.0,
                "signal_multiplier": 1.0,
                "filter_passed": True  # Allow signals if analysis fails
            }


class ScalpingStrategy:
    """
    Ultra-optimized scalping strategy using event-driven technical analysis.
    Memory-efficient, CPU-optimized, mathematically equivalent to traditional indicators.
    """

    def __init__(self, config: Dict[str, Any], risk_manager=None):
        """
        Initialize optimized scalping strategy.

        Args:
            config: Strategy configuration
            risk_manager: Optional risk manager integration
        """
        self.name = "OptimizedScalpingStrategy"
        self.config = config
        self.risk_manager = risk_manager

        # Trading parameters
        self.symbol = config.get('symbol', 'BTC-USDT')
        self.position_size_pct = config.get('position_size_pct', 0.02)  # 2% of portfolio
        self.stop_loss_pct = config.get('stop_loss_pct', 0.01)  # 1% stop loss
        self.take_profit_pct = config.get('take_profit_pct', 0.02)  # 2% take profit

        # Indicator thresholds
        self.rsi_overbought = config.get('rsi_overbought', 70)
        self.rsi_oversold = config.get('rsi_oversold', 30)
        self.macd_threshold = config.get('macd_threshold', 0.0)

        # OPTIMIZED: Use OptimizedTechnicalAnalyzer instead of manual calculations
        analyzer_config = {
            'ema_period': config.get('ema_period', 14),
            'rsi_period': config.get('rsi_period', 14),
            'macd_fast': config.get('macd_fast', 12),
            'macd_slow': config.get('macd_slow', 26),
            'macd_signal': config.get('macd_signal', 9),
            'price_history_size': config.get('price_history_size', 100),
            'event_config': config.get('event_config', {
                'min_price_change_pct': 0.0005,  # 0.05%
                'min_volume_multiplier': 2.0,     # 2x average
                'max_time_gap_seconds': 30        # Process every 30s max
            })
        }

        self.analyzer = OptimizedTechnicalAnalyzer(analyzer_config)

        # Trading state
        self.current_position = 0  # 0: no position, 1: long, -1: short
        self.entry_price = 0.0
        self.stop_loss_price = 0.0
        self.take_profit_price = 0.0

        # Performance tracking
        self.trades_executed = 0
        self.winning_trades = 0
        self.total_pnl = 0.0

        # Signal tracking for analysis
        self.last_signals = {}

        logger.info(f"🚀 {self.name} initialized with optimized analyzer")

    def add_price_data(self, price: float, volume: float = 0, timestamp: Optional[float] = None) -> Optional[Dict[str, Any]]:
        """
        Process price update with intelligent event filtering.

        OPTIMIZATION: Event-driven processing reduces CPU by 70-90%

        Args:
            price: Current price
            volume: Trading volume
            timestamp: Data timestamp

        Returns:
            Trading signal dict or None if no action needed
        """
        start_time = time.time()

        # OPTIMIZED: Analyzer handles event filtering internally
        processed = self.analyzer.add_price_data(price, volume, timestamp)

        STRATEGY_LATENCY.labels(strategy=self.name).observe(time.time() - start_time)

        if not processed:
            # Event filtered - no processing needed (70-90% reduction)
            return None

        # Generate trading signals using optimized indicators
        signals = self._generate_signals()
        self.last_signals = signals

        # Check for entry/exit conditions
        action = self._evaluate_trading_logic(signals, price)

        if action:
            return self._create_trade_signal(action, signals, price)

        return None

    def _generate_signals(self) -> Dict[str, Any]:
        """Generate all trading signals using optimized analyzer."""
        signals = {}

        # OPTIMIZED: Get pre-computed indicators from analyzer
        ema = self.analyzer.get_ema()
        rsi = self.analyzer.get_rsi()
        macd_data = self.analyzer.get_macd()

        # EMA signals
        if ema is not None:
            current_price = self.analyzer.indicator_values.get('price', 0)
            signals['ema_above'] = current_price > ema
            signals['ema_below'] = current_price < ema

        # RSI signals
        if rsi is not None:
            signals['rsi_overbought'] = rsi > self.rsi_overbought
            signals['rsi_oversold'] = rsi < self.rsi_oversold
            signals['rsi_value'] = rsi

        # MACD signals
        if macd_data:
            macd_line, signal_line, histogram = macd_data
            signals['macd_bullish'] = macd_line > signal_line and histogram > self.macd_threshold
            signals['macd_bearish'] = macd_line < signal_line and histogram < -self.macd_threshold
            signals['macd_line'] = macd_line
            signals['macd_signal'] = signal_line
            signals['macd_histogram'] = histogram

        return signals

    def _evaluate_trading_logic(self, signals: Dict[str, Any], current_price: float) -> Optional[str]:
        """
        Evaluate trading logic based on signals.

        Scalping Strategy Rules:
        - Long: EMA above price + RSI oversold + MACD bullish
        - Short: EMA below price + RSI overbought + MACD bearish
        - Exit: Stop loss or take profit hit
        """
        # Check exit conditions first
        if self.current_position != 0:
            if self._should_exit_position(current_price):
                return "CLOSE"

        # Check entry conditions
        elif self.analyzer.is_initialized():  # Only trade when indicators ready
            # Long entry
            if (signals.get('ema_above', False) and
                signals.get('rsi_oversold', False) and
                signals.get('macd_bullish', False)):
                return "BUY"

            # Short entry
            elif (signals.get('ema_below', False) and
                  signals.get('rsi_overbought', False) and
                  signals.get('macd_bearish', False)):
                return "SELL"

        return None

    def _should_exit_position(self, current_price: float) -> bool:
        """Check if position should be closed."""
        if self.current_position == 0:
            return False

        # Stop loss check
        if self.current_position == 1:  # Long position
            if current_price <= self.stop_loss_price or current_price >= self.take_profit_price:
                return True
        elif self.current_position == -1:  # Short position
            if current_price >= self.stop_loss_price or current_price <= self.take_profit_price:
                return True

        return False

    def _create_trade_signal(self, action: str, signals: Dict[str, Any], price: float) -> Dict[str, Any]:
        """Create standardized trade signal."""
        signal = {
            'action': action,
            'symbol': self.symbol,
            'price': price,
            'timestamp': time.time(),
            'signals': signals.copy(),
            'strategy': 'optimized_scalping'
        }

        if action in ['BUY', 'SELL']:
            # Calculate position size and levels
            signal.update(self._calculate_position_details(action, price))
            self._update_position_state(action, price)
        elif action == 'CLOSE':
            # Calculate PnL
            pnl = self._calculate_pnl(price)
            signal['pnl'] = pnl
            signal['position_size'] = abs(self.current_position)
            self._update_position_state(action, price)

        # Record signal generation
        SIGNALS_GENERATED.labels(
            strategy=self.name,
            signal_type=action.lower()
        ).inc()

        return signal

    def _calculate_position_details(self, action: str, price: float) -> Dict[str, Any]:
        """Calculate position size, stop loss, and take profit."""
        # Position size based on percentage of portfolio
        position_size = self.position_size_pct  # This would be calculated based on actual portfolio value

        # Stop loss and take profit levels
        if action == 'BUY':
            stop_loss = price * (1 - self.stop_loss_pct)
            take_profit = price * (1 + self.take_profit_pct)
        else:  # SELL
            stop_loss = price * (1 + self.stop_loss_pct)
            take_profit = price * (1 - self.take_profit_pct)

        return {
            'position_size': position_size,
            'stop_loss': stop_loss,
            'take_profit': take_profit,
            'leverage': 1.0  # No leverage for scalping
        }

    def _update_position_state(self, action: str, price: float) -> None:
        """Update internal position state."""
        if action == 'BUY':
            self.current_position = 1
            self.entry_price = price
            self.stop_loss_price = price * (1 - self.stop_loss_pct)
            self.take_profit_price = price * (1 + self.take_profit_pct)
        elif action == 'SELL':
            self.current_position = -1
            self.entry_price = price
            self.stop_loss_price = price * (1 + self.stop_loss_pct)
            self.take_profit_price = price * (1 - self.take_profit_pct)
        elif action == 'CLOSE':
            # Calculate and record PnL
            pnl = self._calculate_pnl(price)
            self.total_pnl += pnl

            if pnl > 0:
                self.winning_trades += 1

            self.trades_executed += 1

            # Reset position
            self.current_position = 0
            self.entry_price = 0.0
            self.stop_loss_price = 0.0
            self.take_profit_price = 0.0

    def _calculate_pnl(self, exit_price: float) -> float:
        """Calculate profit/loss for closed position."""
        if self.current_position == 0 or self.entry_price == 0:
            return 0.0

        if self.current_position == 1:  # Long position
            return (exit_price - self.entry_price) / self.entry_price
        else:  # Short position
            return (self.entry_price - exit_price) / self.entry_price

    def get_performance_stats(self) -> Dict[str, Any]:
        """Get strategy performance statistics."""
        analyzer_stats = self.analyzer.get_performance_stats()

        win_rate = (self.winning_trades / self.trades_executed * 100) if self.trades_executed > 0 else 0

        return {
            'trades_executed': self.trades_executed,
            'winning_trades': self.winning_trades,
            'win_rate_pct': win_rate,
            'total_pnl': self.total_pnl,
            'current_position': self.current_position,
            'analyzer_stats': analyzer_stats
        }

    def reset(self) -> None:
        """Reset strategy state."""
        self.analyzer.reset()
        self.current_position = 0
        self.entry_price = 0.0
        self.stop_loss_price = 0.0
        self.take_profit_price = 0.0
        self.trades_executed = 0
        self.winning_trades = 0
        self.total_pnl = 0.0
        self.last_signals = {}

# Required fields for data completeness scoring
required_fields = [
    'price', 'volume', 'timestamp', 'bid', 'ask',
    'ema', 'rsi', 'macd_line', 'macd_signal', 'macd_histogram'
]
